#!/bin/bash 
bold="\e[1m"
red="\e[31m"
green="\e[32m"
blue="\e[34m"
end="\e[0m"
VERSION="2022-06-1"
icon="\U2705"
PLC=$(pwd) 

# Output will be Here ToolKit/output/

spinner(){
	processing="${1}"
	while true; 
	do
		dots=(
			"/"
			"-"
			"\\"
			"|"
			)
		for dot in ${dots[@]};
		do
			printf "[${dot}] ${processing} \U1F50E"
			printf "                                    \r"
			sleep 0.3
		done
		
	done
}

echo -e -n "$green Enter Company Name : $end" ; read company_name
echo -e -n "$green Enter The domain : $end" ; read domain_name


HouseKeeping(){
mkdir -p output/$company_name/$domain_name/notAliveSub/
mkdir -p output/$company_name/$domain_name/aliveSub/
mkdir -p output/$company_name/$domain_name/techFilter/

echo -e "$blue Directories Created Successfully. $end"

}

SubENumTool(){
	subenum -d $domain_name -o output/$company_name/$domain_name/notAliveSub/notAlive-$domain_name.txt
	echo -e ""
	echo -e "$green[-] SubENumTool for $domain_name  Count:  $end:$(wc -l < output/$company_name/$domain_name/notAliveSub/notAlive-$domain_name.txt )"
}

HttpxCheckAlive(){
	
	echo -e ""
	echo -e "$blue  Checking Alive. $end"
	echo -e ""
	
	spinner "${red}Alive${end}" & PID="$!" 
	cat output/$company_name/$domain_name/notAliveSub/notAlive-$domain_name.txt | httpx -sc -td -fr -title -server -timeout 70 1> output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt 2> /dev/null
	kill ${PID}
	echo -e "$green[-] Alive Subdomains Result for $domain_name $end:$blue $(wc -l < output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt ) $end" 

}

techFiltering(){
  			    cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i IIS | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/IIS.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i nginx | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/Nginx.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i nuxt | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/Nuxt.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i openresty | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/OpenResty.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i php | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/PHP.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i ruby | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/Ruby.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i s3 | cut -d " " -f1 > output/$company_name/$domain_name/techFilter/S3.txt
                cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i /s/ | cut -d " " -f1 >> output/$company_name/$domain_name/techFilter/SalesForce.txt
	        cat output/$company_name/$domain_name/aliveSub/alive-$domain_name.txt  | grep -i /aura | cut -d " " -f1 >> output/$company_name/$domain_name/techFilter/SalesForce.txt

		echo -e "$green[-] Technology IIS $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/IIS.txt ) $end"
		echo -e "$green[-] Technology nginx $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/Nginx.txt ) $end"
		echo -e "$green[-] Technology Nuxt $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/Nuxt.txt ) $end"
		echo -e "$green[-] Technology OpenResty $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/OpenResty.txt ) $end"
		echo -e "$green[-] Technology PHP $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/PHP.txt ) $end"
		echo -e "$green[-] Technology Ruby $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/Ruby.txt ) $end"
		echo -e "$green[-] Technology S3 AWS $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/S3.txt ) $end"
       	echo -e "$green[-] Technology SalesForce for $domain_name $end:$blue $(wc -l < output/$company_name/$domain_name/techFilter/SalesForce.txt ) $end" | teleman
          
}

HouseKeeping
SubENumTool
HttpxCheckAlive
techFiltering
